// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CriarBackup() {
  return window['go']['handlers']['BackupHandler']['CriarBackup']();
}

export function ListarBackups() {
  return window['go']['handlers']['BackupHandler']['ListarBackups']();
}

export function RestaurarBackup(arg1) {
  return window['go']['handlers']['BackupHandler']['RestaurarBackup'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['BackupHandler']['Startup'](arg1);
}
