// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function AdicionarEvento(arg1:handlers.Evento):Promise<void>;

export function AtualizarEvento(arg1:handlers.Evento):Promise<void>;

export function CarregarEventos():Promise<Array<handlers.Evento>>;

export function DeletarEvento(arg1:string):Promise<void>;

export function SalvarEventos(arg1:Array<handlers.Evento>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
