// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdicionarEvento(arg1) {
  return window['go']['handlers']['CalendarioHandler']['AdicionarEvento'](arg1);
}

export function AtualizarEvento(arg1) {
  return window['go']['handlers']['CalendarioHandler']['AtualizarEvento'](arg1);
}

export function CarregarEventos() {
  return window['go']['handlers']['CalendarioHandler']['CarregarEventos']();
}

export function DeletarEvento(arg1) {
  return window['go']['handlers']['CalendarioHandler']['DeletarEvento'](arg1);
}

export function SalvarEventos(arg1) {
  return window['go']['handlers']['CalendarioHandler']['SalvarEventos'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['CalendarioHandler']['Startup'](arg1);
}
