// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function CarregarCanvas():Promise<handlers.CanvasData>;

export function DeletarImagem(arg1:string):Promise<void>;

export function LimparImagensOrfas(arg1:Array<string>):Promise<void>;

export function SalvarCanvas(arg1:Array<handlers.NodeData>,arg2:Array<handlers.EdgeData>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UploadImagem(arg1:string,arg2:Array<number>,arg3:string):Promise<string>;
