// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CarregarCanvas() {
  return window['go']['handlers']['IdeiasHandler']['CarregarCanvas']();
}

export function DeletarImagem(arg1) {
  return window['go']['handlers']['IdeiasHandler']['DeletarImagem'](arg1);
}

export function LimparImagensOrfas(arg1) {
  return window['go']['handlers']['IdeiasHandler']['LimparImagensOrfas'](arg1);
}

export function SalvarCanvas(arg1, arg2) {
  return window['go']['handlers']['IdeiasHandler']['SalvarCanvas'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['handlers']['IdeiasHandler']['Startup'](arg1);
}

export function UploadImagem(arg1, arg2, arg3) {
  return window['go']['handlers']['IdeiasHandler']['UploadImagem'](arg1, arg2, arg3);
}
