// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdicionarLink(arg1) {
  return window['go']['handlers']['LinksHandler']['AdicionarLink'](arg1);
}

export function AtualizarLink(arg1) {
  return window['go']['handlers']['LinksHandler']['AtualizarLink'](arg1);
}

export function CarregarLinks() {
  return window['go']['handlers']['LinksHandler']['CarregarLinks']();
}

export function DeletarLink(arg1) {
  return window['go']['handlers']['LinksHandler']['DeletarLink'](arg1);
}

export function SalvarLinks(arg1) {
  return window['go']['handlers']['LinksHandler']['SalvarLinks'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['LinksHandler']['Startup'](arg1);
}
