// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function AdicionarLink(arg1:handlers.Link):Promise<void>;

export function AtualizarLink(arg1:handlers.Link):Promise<void>;

export function CarregarLinks():Promise<Array<handlers.Link>>;

export function DeletarLink(arg1:string):Promise<void>;

export function SalvarLinks(arg1:Array<handlers.Link>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
