// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function AdicionarObjetivo(arg1:handlers.Objetivo):Promise<void>;

export function AtualizarObjetivo(arg1:handlers.Objetivo):Promise<void>;

export function CarregarObjetivos():Promise<Array<handlers.Objetivo>>;

export function DeletarObjetivo(arg1:string):Promise<void>;

export function SalvarObjetivos(arg1:Array<handlers.Objetivo>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
