// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdicionarObjetivo(arg1) {
  return window['go']['handlers']['ObjetivosHandler']['AdicionarObjetivo'](arg1);
}

export function AtualizarObjetivo(arg1) {
  return window['go']['handlers']['ObjetivosHandler']['AtualizarObjetivo'](arg1);
}

export function CarregarObjetivos() {
  return window['go']['handlers']['ObjetivosHandler']['CarregarObjetivos']();
}

export function DeletarObjetivo(arg1) {
  return window['go']['handlers']['ObjetivosHandler']['DeletarObjetivo'](arg1);
}

export function SalvarObjetivos(arg1) {
  return window['go']['handlers']['ObjetivosHandler']['SalvarObjetivos'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['ObjetivosHandler']['Startup'](arg1);
}
