// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function AdicionarPasso(arg1:handlers.Passo):Promise<void>;

export function AtualizarPasso(arg1:handlers.Passo):Promise<void>;

export function CarregarPassos():Promise<Array<handlers.Passo>>;

export function DeletarPasso(arg1:string):Promise<void>;

export function MoverPasso(arg1:string,arg2:string):Promise<void>;

export function SalvarPassos(arg1:Array<handlers.Passo>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleConcluido(arg1:string):Promise<void>;
