// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdicionarPasso(arg1) {
  return window['go']['handlers']['PassosHandler']['AdicionarPasso'](arg1);
}

export function AtualizarPasso(arg1) {
  return window['go']['handlers']['PassosHandler']['AtualizarPasso'](arg1);
}

export function CarregarPassos() {
  return window['go']['handlers']['PassosHandler']['CarregarPassos']();
}

export function DeletarPasso(arg1) {
  return window['go']['handlers']['PassosHandler']['DeletarPasso'](arg1);
}

export function MoverPasso(arg1, arg2) {
  return window['go']['handlers']['PassosHandler']['MoverPasso'](arg1, arg2);
}

export function SalvarPassos(arg1) {
  return window['go']['handlers']['PassosHandler']['SalvarPassos'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['PassosHandler']['Startup'](arg1);
}

export function ToggleConcluido(arg1) {
  return window['go']['handlers']['PassosHandler']['ToggleConcluido'](arg1);
}
