// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdicionarTarefa(arg1) {
  return window['go']['handlers']['PlanejamentoHandler']['AdicionarTarefa'](arg1);
}

export function AtualizarTarefa(arg1, arg2) {
  return window['go']['handlers']['PlanejamentoHandler']['AtualizarTarefa'](arg1, arg2);
}

export function CarregarQuadro() {
  return window['go']['handlers']['PlanejamentoHandler']['CarregarQuadro']();
}

export function DeletarTarefa(arg1, arg2) {
  return window['go']['handlers']['PlanejamentoHandler']['DeletarTarefa'](arg1, arg2);
}

export function MoverTarefa(arg1, arg2, arg3) {
  return window['go']['handlers']['PlanejamentoHandler']['MoverTarefa'](arg1, arg2, arg3);
}

export function SalvarQuadro(arg1) {
  return window['go']['handlers']['PlanejamentoHandler']['SalvarQuadro'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['PlanejamentoHandler']['Startup'](arg1);
}
