// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function AdicionarTarefa(arg1:handlers.Tarefa):Promise<void>;

export function AtualizarTarefa(arg1:handlers.Tarefa,arg2:string):Promise<void>;

export function CarregarQuadro():Promise<handlers.QuadroKanban>;

export function DeletarTarefa(arg1:string,arg2:string):Promise<void>;

export function MoverTarefa(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SalvarQuadro(arg1:handlers.QuadroKanban):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
